sudo: required
language: node_js
node_js:
  - 6
services:
  - mongodb
  - docker
after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - if [ "$BRANCH" == "master" ]; then
    docker build -t delta62/oscar-api .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push delta62/oscar-api;
    fi
